### PR TITLE
icalrecur.c: fix handling of BYWEEKNO with no BYDAY to use the day of…

### PR DESCRIPTION
**Pull request by ksmurchison**
… week from DTSTART rather than day of month

Fix for issue #438, assuming that we agree that this is the proper handling.  FWIW, I asked a former CalConnect colleague (and CalendarServer developer) about this and he agreed that in this case, it makes more sense to use day of week rather than day of month

### CODE REVIEW

**Comment by winterz** [comment]
ok by me.
@ksuther any objections?

please also mention the change in the ReleaseNotes.
Oh, and commit to the 3.0 branch

**Review by ksuther — APPROVED** [review]
Seems reasonable to me too.

**Comment by ksmurchison** [comment]
@winterz Do you want me to cherry-pick the other BYWEEKNO changes from master to 3.0?  This one only changes what data we inherit from DTSTART, but the others are needed to fix a host of other BYWEEKNO issues.

**Comment by winterz** [comment]
> @winterz Do you want me to cherry-pick the other BYWEEKNO changes from master to 3.0? This one only changes what data we inherit from DTSTART, but the others are needed to fix a host of other BYWEEKNO issues.

yes please cherry-pick the BYWEEKNO changes from master to 3.0
and don't forget the ReleaseNotes:)

**Pull request merged**
