### PR TITLE
icalvalue.c: truncate long GEO values rather than erroring

### PR DESCRIPTION
**Pull request by ksmurchison**

### CODE REVIEW

**Review by winterz — APPROVED** [review]
this version works for me on Windows.  although GetNumberFormat still needs to be dealt with.  then I'm wondering why we even need to support GetNumberFormat.

**Comment by ksmurchison** [comment]
Does GetNumberFormat do anything different than what we are doing manually?

**Comment by ksmurchison** [comment]
> > Does GetNumberFormat do anything different than what we are doing manually?
> 
> Best I can find about GetNumberFormat is that it was introduced by me in 2011 when doing some porting for WinCE, which is long dead.
> 
> I think we can remove it in a follow-on patch and rely on what we're doing manually.

Should I remove the code that I added to that block then?

**Comment by winterz** [comment]
> > > Does GetNumberFormat do anything different than what we are doing manually?
> > 
> > 
> > Best I can find about GetNumberFormat is that it was introduced by me in 2011 when doing some porting for WinCE, which is long dead.
> > I think we can remove it in a follow-on patch and rely on what we're doing manually.
> 
> Should I remove the code that I added to that block then?

yes.  change your patch to only deal with the stuff we're doing manually
then I will make a follow-on patch that removes GetNumberFormat everywhere in the code.

**Comment by ksmurchison** [comment]
@winterz Done

**Pull request merged**
