### PR TITLE
co-locate the MEMORY_CONSISTENCY settings in icalmemory.c

### PR DESCRIPTION
**Pull request by winterz**
Put all the possible settings for the MEMORY_CONSISTENCY in 1 place, icalmemory.c

### CODE REVIEW

**Comment by winterz** [comment]
@minichma how do you feel about this?  since there were no other consumers for the ICALMEMORY_DEFAULT_* macros I don't see a reason to have them in config.h.cmake

**Comment by minichma** [comment]
Having the settings in config.h would allow compile-time replacement without the need for changing the 'actual' code base. Here at Tapkey we use libical on embedded controllers (e.g. on Nordic's nRF52), where program size is a major concern. Replacing malloc at runtime is therefore not sufficient, as we also need to avoid linking it. By having malloc configured as default inside icalmemory, replacing would require us to fork the code base and patch icalmemory.c. By configuring the defauls in config.h, changing the code base would be avoided. However, in this very use case, centrally defining the defaults in config.h would be sufficient, whereas having top-level cmake settings would not be required.

That said, the described use case might not be very common and forking might be required anyways is such cases. So the benefit of improved configurability might not be worth the additional code and complexity.

As an intermediate solution we could centrally define the defaults in config.h.cmake but without having top-level cmake settings.

**Comment by winterz** [comment]
I certainly don't want to make any changes that require a fork on your part.
Ideally you'd only need to change your CMake and/or CCFLAGS/LDFLAGS.

Is the current code good enough to avoid forking, or is more work needed?

I assume you can compile with whatever -DICALMEMORY_DEFAULT_* values you want the way things are right now.
we could also add CMake options for LIBICAL_USE_MEMORY_SYSTEM_BOO and change config.h.cmake, for example:
```
#if(LIBICAL_USE_MEMORY_SYSTEM_BOO)
#define ICALMEMORY_DEFAULT_MALLOC boo_malloc
#define ICALMEMORY_DEFAULT_REALLOC boo_realloc
#define ICALMEMORY_DEFAULT_FREE boo_free
#elif(LIBICAL_USE_MEMORY_SYSTEM_GOO)
#define ICALMEMORY_DEFAULT_MALLOC goo_malloc
#define ICALMEMORY_DEFAULT_REALLOC goo_realloc
#define ICALMEMORY_DEFAULT_FREE goo_free
#else
#define ICALMEMORY_DEFAULT_MALLOC malloc
#define ICALMEMORY_DEFAULT_REALLOC realloc
#define ICALMEMORY_DEFAULT_FREE free
#endif
```
or some-such

**Comment by minichma** [comment]
Yes, the current (`master`) version certainly is good enough, because it allows us defining `malloc` as empty, therefore avoiding compiling and linking it into libical. From our side it would also be ok to have a single cmake option like 'ICAL_CUSTOM_MALLOC` that, if true, doesn't set a default at all and instead requires the user to set custom functions.

**Comment by winterz** [comment]
abandoning this.
will look at adding a CMake option for ICAL_CUSTOM_MALLOC

**Pull request closed without merging**
