### PR TITLE
icalcomponent_foreach_recurrence(): add support for RDATE;VALUE=PERIOD

### PR DESCRIPTION
**Pull request by ksmurchison**
Potential fix for issue #637.  I did this on an airplane so it needs to be sanity checked.

### CODE REVIEW

**Comment by winterz** [comment]
Splint issue:

```
src/libical/icalcomponent.c: (in function icalcomponent_foreach_recurrence)
src/libical/icalcomponent.c:972:17: Assignment of int to time_t: rdate_duration = icaldurationtype_as_int(rdate_period.period.duration)
  To allow arbitrary integral types to match long unsigned, use +longintegral.
```

**Review by winterz — COMMENTED** [review]
looks good except for the 1 splint issue.
wouldn't hurt to add some more test cases to regression.c.

**Comment by ksmurchison** [comment]
> looks good except for the 1 splint issue. wouldn't hurt to add some more test cases to regression.c.

@winterz What other tests would you suggest?

**Comment by winterz** [comment]
> > looks good except for the 1 splint issue.
> 
> Does typecasting the value to icaltime_t solve the issue. E.g.: rdate_duration = (icaltime_t) icaldurationtype_as_int(...)
> 
yep

> > wouldn't hurt to add some more test cases to regression.c.
> 
> @winterz What other tests would you suggest?
* starttime with duration (rather than endtime)
*  the endtime is before the starttime (badness)


btw: should
 "RDATE;VALUE=PERIOD:20180223T020000Z/20180223T030000Z," 
be
 "RDATE;VALUE=PERIOD:20180223T020000Z/20180223T030000Z\n"

**Comment by ksmurchison** [comment]
> > > looks good except for the 1 splint issue.
> > 
> > 
> > Does typecasting the value to icaltime_t solve the issue. E.g.: rdate_duration = (icaltime_t) icaldurationtype_as_int(...)
> 
> yep
> 
> > > wouldn't hurt to add some more test cases to regression.c.
> > 
> > 
> > @winterz What other tests would you suggest?
> 
>     * starttime with duration (rather than endtime)
> 
>     * the endtime is before the starttime (badness)

Neither of these really impact RDATE;VALUE-PERIOD handling specifically.  They would be more appropriate for general recurrence handling.

> btw: should "RDATE;VALUE=PERIOD:20180223T020000Z/20180223T030000Z," be "RDATE;VALUE=PERIOD:20180223T020000Z/20180223T030000Z\n"

Only if we adding folding whitespace following the linefeed.  I'm fine doing that if you prefer it.

**Comment by winterz** [comment]
ok.  then good to go after fixing that icaltime_t cast

**Comment by ksmurchison** [comment]
Done

**Pull request merged**
