### PR TITLE
Internally represent GEO properties as text

### PR DESCRIPTION
**Pull request by winterz**
This allows arbitrary precision for the GEO values

fixes: #531

### CODE REVIEW

**Comment by rsto** [comment]
Would this break compatibility with the Python wrapper? I see in design-data/value-types.cvs that it returns a tuple in Python, but is the current Python return value a tuple of floats, and now would become a tuple of strings?

Incidentally, I am currently also working on the GEO property. We plan to propose also allowing URI value types ([RFC 5870](https://www.rfc-editor.org/rfc/rfc5870.html)) for the `GEO` property, e.g.

    GEO;VALUE=URI:geo:37.786971,-122.399677;u=35

The geo: URI scheme allows for three-dimensional coordinates, uncertainty and a couple of additional improvements over the iCalendar GEO value. Apple is using them in the `X-APPLE-STRUCTURED-LOCATION` properties.

I think that this is independent of the change in PR, but I thought I share the news.

**Review by ksmurchison — APPROVED** [review]
LGTM

**Comment by winterz** [comment]
> Would this break compatibility with the Python wrapper? I see in design-data/value-types.cvs that it returns a tuple in Python, but is the current Python return value a tuple of floats, and now would become a tuple of strings?

Yes it will.  I can fix.  Except this brings up even more issues:
 - the test.py is written in python2 => needs to be converted to python3
 - test.py should be invoked as part of the 'make test' target
 - actually, all of src/python should be ported to python3

> 
> Incidentally, I am currently also working on the GEO property. We plan to propose also allowing URI value types ([RFC 5870](https://www.rfc-editor.org/rfc/rfc5870.html)) for the `GEO` property, e.g.
> 
> ```
> GEO;VALUE=URI:geo:37.786971,-122.399677;u=35
> ```
> 
> The geo: URI scheme allows for three-dimensional coordinates, uncertainty and a couple of additional improvements over the iCalendar GEO value. Apple is using them in the `X-APPLE-STRUCTURED-LOCATION` properties.
> 
> I think that this is independent of the change in PR, but I thought I share the news.
And very good news indeed.  That's great!

**Comment by winterz** [comment]
um.. side question.  are you actively using src/python?  I just realized we don't even build src/python 
maybe you're talking about the stuff in libical-glib?  If so, I handled that so the python API does not change.

**Comment by winterz** [comment]
@rsto what's missing is the validation of the geo values (ie. latitiude <=abs(90.0) and longitude <= abs(180.) or whatever the standard says

maybe you can add that when working on the RFC 5870 stuff?

**Comment by rsto** [comment]
> um.. side question. are you actively using src/python?

No, I just looked at the Python mapping for GEO when I learned how the values-types.csv file works.

> what's missing is the validation of the geo values

I'll make sure to validate these when I update the GEO handling code.

**Pull request merged**
