### PR TITLE
issue #428: runtime setting to ignore invalid BYxxx part combos in RR…

### PR DESCRIPTION
**Pull request by ksmurchison**
…ULEs

I wondering if we should check validity in icalrecurrencetype_from_string()?  That's really the only API that we have for creating an icalrecurrencetype, other than populating the struct manually

### CODE REVIEW

**Review by ksuther — COMMENTED** [review]
Returning an error in `icalrecurrencetype_from_string` makes sense to me, as it already returns errors in other scenarios. That would make it easier to use the API for validation instead of discovering that a RRULE is invalid only when you try to use it.

This should also have quirks mode tests for `ICAL_RRULE_IGNORE_INVALID`.

In https://github.com/libical/libical/issues/428#issuecomment-709361693 you asked if we should apply this to all illegal rules. I haven't thought through every permutation, but since this is working around a very specific problem I'm inclined to say we have a specific set of workarounds to allow interoperability but otherwise leave things strict. That way we have exact tests and documentation for why we accept particular incorrect behavior while not inadvertently introducing our own (and other parsers then having to account for libical's quirky behavior in the future).

**Comment by ksmurchison** [comment]
I think if we use this PR rather than #429 then the question of whether we want to be strict or lenient is up to the client.  The default mode will be strict and in the case of BYMONTHDAY + BYYEARDAY, the client can choose to be lenient.

I will look into expanding this option to also work at parse time.

**Comment by ksmurchison** [comment]
@ksuther @winterz  Updated to include parse time check (with change to regression.c which happens to include an invalid RRULE)

**Comment by ksmurchison** [comment]
Where do we stand on this one?

**Comment by ksuther** [comment]
This seems reasonable to me. So far the only mismatched case I've seen is the original one I reported, but we may turn this mode on in Fantastical and see if anyone reports anything else unexpected :)

**Comment by ksmurchison** [comment]
Hmm. I'm wondering if we should strip the invalid BY* parts so we don't output bad RRULEs

**Comment by ksmurchison** [comment]
Updated to ignore invalid BY* part data so icalrecurrencetype_as_string() doesn't output it

**Comment by ksmurchison** [comment]
@winterz @ksuther Looking for one final set of eyes to look at this before I merge.

**Comment by ksuther** [comment]
Late to the party on this one, but it still makes sense to me. I mentioned this before, but I'm curious if any weird unintended parsing get encountered in the wild that don't make any sense at all. I guess time will tell :)

**Pull request merged**
