### PR TITLE
Apply changes found during Evolution Data Server port to libical-glib

### PR DESCRIPTION
**Pull request by tintou**
A series of patches found by Milan Crha (mcrha).
The description of each change is written in the commit message directly.

### CODE REVIEW

**Comment by winterz** [comment]
do we want this in the 3.0 branch for a possible 3.0.5 release?

**Comment by tintou** [comment]
From Milan:
That would be ideal, even it changes libical-glib API. On the other hand, I'd guess it's not used by anyone yet. An interesting approach would be to add something like LIBICAL_GLIB_UNSTABLE_API define as a requirement for the time being, to express that things can change. At least until the main consumer (evolution-data-server, possibly with its clients) is ported. Definitely do not hurry with the 3.0.5 just because of these changes.

**Comment by winterz** [comment]
How about I give you commit privileges so you can do whatever you need for the libical-glib stuff?

My only concern would be binary and source compatibility.  I'll keep an eye on your changes and we can discuss how to handle those as the need arises.
-Allen

**Comment by tintou** [comment]
Answer from Milan:
- giving commit rights to me (via tintou) would help, the done (and coming, if any) changes are strictly to libical-glib
- there are already API changes in the done patches, which makes it harder for the compatibility, but it's unlikely the libical-glib is used too much, thus I'd not be afraid of it
- the offered LIBICAL_GLIB_UNSTABLE_API define mentioned above would probably make things clearer, and I'm in favour to just do it (as an additional change)

**Comment by tintou** [comment]
@winterz thanks for the commit access :tada: 
Two questions that Milan would like you to give an explicit go/no-go:
 * The patches for libical-glib are going to break its API/ABI stability. Giving that there are currently no known user of libical-glib, would it be alright to do it. It would also be greatly appreciated to have it in the 3.0 release.
 * Would a `LIBICAL_GLIB_UNSTABLE_API` define guard for libical-glib be alright to prevent people to think that libical-glib is stable for now.

**Comment by winterz** [comment]
> @winterz thanks for the commit access tada
> Two questions that Milan would like you to give an explicit go/no-go:
> 
>     * The patches for libical-glib are going to break its API/ABI stability. Giving that there are currently no known user of libical-glib, would it be alright to do it. It would also be greatly appreciated to have it in the 3.0 release.
> 
>     * Would a `LIBICAL_GLIB_UNSTABLE_API` define guard for libical-glib be alright to prevent people to think that libical-glib is stable for now.

Ok. 
Please mention it in the ReadMe that we currently do not guarantee source or binary compatibility in the libical-glib

**Pull request merged**
