### PR TITLE
On Windows, the bswap_32 macro is defined later on.

### PR DESCRIPTION
**Pull request by ajacoutot**
That's a follow up of https://github.com/libical/libical/pull/204 .
Sorry for missing it.

### CODE REVIEW

**Comment by winterz** [comment]
I notice that FreeBSD has the bswapXX functions defined in machine/bswap.h

does OpenBSD also have machine/bswap.h?

**Comment by ajacoutot** [comment]
Hi Allen.
No, OpenBSD does not bundle such header. We have no definition for bswapXX, only swapXX.

**Comment by winterz** [comment]
then how about if we go back to what we had previously, but add 
#if defined(__OPENBSD__)
#define bswap_32 swap32
#endif
before the #if defined(_MSC_VER) section

**Comment by ajacoutot** [comment]
Oh I am absolutely fine with me yes. I originally tried to make it a bit more generic, but your proposal will work just fine :-)
You need to use this though:
#if defined(__OpenBSD__)

**Pull request closed without merging**
