### PR TITLE
misc: Update sources to more modern C

### PR DESCRIPTION
**Pull request by mcrha**
The code fails to build when having enabled (gcc) warnings:
   -Werror=implicit
   -Werror=implicit-function-declaration
   -Werror=implicit-int
   -Werror=int-conversion
   -Werror=old-style-definition
   -Werror=strict-prototypes

### CODE REVIEW

**Comment by winterz** [comment]
non-modern stuff will sneak back in unless we add those compile options by default.

in the top-level CMakeLists.txt maybe we need to add
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror=implicit -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=old-style-definition -Werror=strict-prototypes")
```
I also didn't want to force "modern C" into the 3.0 branch.  this would be fine in the master branch though.
Do we need this in 3.0?

**Comment by mcrha** [comment]
I can modify the CMakeLists.txt. Not sure about the -Werror... thing, maybe just enable the warning is enough.

With respect of the 3.0, I've got an impression that it's the branch for the current development. It's not needed for the 3.0 at the moment and it won't be needed for some time. The idea behind this is from the Fedora's proposed change: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/CJXKTLXJUPZ4F2C2VQOTNMEA5JAUPMBD/
 I might mention it earlier, I'm sorry.

**Comment by winterz** [comment]
appveyor CI is showing compile errors

**Comment by mcrha** [comment]
> /home/appveyor/projects/libical/src/test/icaltm_test.c:30:25: error: parameter name omitted

aha, they do not like unnamed parameters. It's fixed now.

**Comment by a17r** [comment]
This should fix build with >=clang-16 (error in caldate.c), see also: https://bugs.gentoo.org/880391

**Comment by thesamesam** [comment]
Thanks!

**Pull request merged**
