### PR TITLE
Remove is_utc from icaltimetype

### PR DESCRIPTION
**Pull request by ksuther**
As discussed in #288.

All the tests are passing, but this could use more testing in existing code to make sure there's nothing else that was assuming certain things about how is_utc and zone are set.

For the wrappers:
- I removed is_utc from the wrappers as best I can (Java and libical-glib in particular), but I'm not sure how to test them.
- I removed is_utc from the Python wrapper but it doesn't appear to support the zone field at all, which is a bigger problem aside from this change.
- I left the Net-ICal-Libical wrappers alone, they're so out of date it's probably be better to just remove them.

### CODE REVIEW

**Comment by winterz** [comment]
C:\projects\libical\src\libicalvcal\icalvcal.c(151) : warning C4013: 'icaltimezone_get_utc_timezone' undefined; assuming extern returning int
C:\projects\libical\src\libicalvcal\icalvcal.c(151) : warning C4047: '=' : 'const icaltimezone *' differs in levels of indirection from 'int'

**Comment by winterz** [comment]
Kent, I'm sorry but this patch doesn't compile now.
I managed to resolve the conflicts in the src/java code locally, but the build fails with:

/home/allen/projects/libical/libical/src/libical/icaltz-util.c:459:39: error: ‘icaltimetype {aka struct icaltimetype}’ has no member named ‘is_utc’; did you mean ‘is_date’?
                     prev_daylight_time.is_utc = 1;
                                       ^
/home/allen/projects/libical/libical/src/libical/icaltz-util.c:492:39: error: ‘icaltimetype {aka struct icaltimetype}’ has no member named ‘is_utc’; did you mean ‘is_date’?
                     prev_standard_time.is_utc = 1;
                                       ^
/home/allen/projects/libical/libical/src/libical/icaltz-util.c:506:43: error: ‘icaltimetype {aka struct icaltimetype}’ has no member named ‘is_utc’; did you mean ‘is_date’?
                         prev_daylight_time.is_utc = 1;
                                           ^
/home/allen/projects/libical/libical/src/libical/icaltz-util.c:565:32: error: ‘icaltimetype {aka struct icaltimetype}’ has no member named ‘is_utc’; did you mean ‘is_date’?
         prev_prev_daylight_time.is_utc = 1;
                                ^
/home/allen/projects/libical/libical/src/libical/icaltz-util.c:584:32: error: ‘icaltimetype {aka struct icaltimetype}’ has no member named ‘is_utc’; did you mean ‘is_date’?
         prev_prev_standard_time.is_utc = 1;

**Comment by ksuther** [comment]
I'll fix it when I get a moment.

**Comment by ksuther** [comment]
This got pushed off too long for a simple fix, sorry about that!

Any suggestions about other approaches is more than welcome.

**Comment by winterz** [comment]
Thanks.  1 step closer to 3.0.0

**Comment by winterz** [comment]
Can you add a blurb to the ReleaseNotes. say that the is_utc member of icaltimezone is removed and give suggestions/hints on how to re-write user code without that member.

**Comment by ksuther** [comment]
Does this sound clear?

* Removed is_utc from icaltimetype struct
    * Set icaltimetype.zone to icaltimezone_get_utc_timezone() to change a time to UTC
    * Use icaltime_is_utc() to check if a time is in UTC

**Comment by winterz** [comment]
looks good.

**Comment by ksuther** [comment]
Added in a2bc4844bd54f8431f5c80706e12ef1a94877041

**Pull request merged**
