### PR TITLE
If Until is defined, count not authorised

### PR DESCRIPTION
**Pull request by ad1rie1**
Hello,

this normaly fix the bug #370

Can you check ?

### CODE REVIEW

**Comment by winterz** [comment]
@ksmurchison thoughts on this? you are the recurrence expert :)

**Comment by ksmurchison** [comment]
As stated in bug #370, this just masks the actual problem (and makes an arbitrary decision that UNTIL trumps COUNT).  We probably should add a 'bound' (or 'bounded' or some similar name) tri-state flag to icalrecurrencetype with values of NONE, UNTIL, and COUNT so the creator can explicitly specify if/how the recurrence is bounded, and/or make UNTIL and COUNT part of a union so that only one these mutually exclusive values can be set by the creator.
We should also fix the parser to reject RRULEs that contain both UNTIL and COUNT.

**Comment by ad1rie1** [comment]
hello, 
Any new on that problem ?

**Comment by ksmurchison** [comment]
I think I'd prefer something like the following patch.  It rejects reading and setting COUNT + UNTIL

diff --git a/src/libical/icalderivedvalue.c.in b/src/libical/icalderivedvalue.c.in
index a8d4adef..140b267e 100644
--- a/src/libical/icalderivedvalue.c.in
+++ b/src/libical/icalderivedvalue.c.in
@@ -144,6 +144,9 @@ icalvalue *icalvalue_new_recur(struct icalrecurrencetype v)
 void icalvalue_set_recur(icalvalue *impl, struct icalrecurrencetype v)
 {
     icalerror_check_arg_rv((impl != 0), "value");
+    /* don't allow both count and until */
+    icalerror_check_arg_rv(v.count == 0 || icaltime_is_null_time(v.until),
+                           "recurrencetype");
     icalerror_check_value_type(value, ICAL_RECUR_VALUE);
 
     if (impl->data.v_recur != 0) {
diff --git a/src/libical/icalrecur.c b/src/libical/icalrecur.c
index afacedad..0b3c63c9 100644
--- a/src/libical/icalrecur.c
+++ b/src/libical/icalrecur.c
@@ -611,9 +611,13 @@ struct icalrecurrencetype icalrecurrencetype_from_string(const char *str)
             parser.rt.count = atoi(value);
             /* don't allow count to be less than 1 */
             if (parser.rt.count < 1) r = -1;
+            /* don't allow both count and until */
+            else if (!icaltime_is_null_time(parser.rt.until)) r = -1;
         } else if (strcasecmp(name, "UNTIL") == 0) {
             parser.rt.until = icaltime_from_string(value);
             if (icaltime_is_null_time(parser.rt.until)) r = -1;
+            /* don't allow both count and until */
+            else if (parser.rt.count > 0) r = -1;
         } else if (strcasecmp(name, "INTERVAL") == 0) {
             parser.rt.interval = (short)atoi(value);
             /* don't allow an interval to be less than 1
@@ -720,7 +724,7 @@ char *icalrecurrencetype_as_string_r(struct icalrecurrencetype *recur)
     char temp[20];
     int i, j;
 
-    if (recur->freq == ICAL_NO_RECURRENCE) {
+    if (recur == 0 || recur->freq == ICAL_NO_RECURRENCE) {
         return 0;
     }

**Comment by winterz** [comment]
@ad1rie1 I will close this pull request
@ksmurchison how about creating a new pull request with your new patch?

**Comment by ksmurchison** [comment]
Done as PR #391

**Pull request closed without merging**
