### PR TITLE
Fix several libical-glib issues

### PR DESCRIPTION
**Pull request by mcrha**
Please see the respective commits.

### CODE REVIEW

**Review by tintou — COMMENTED** [review]
vapigen does not use the typelib, how did you trigger this issue?

**Comment by tintou** [comment]
other commits are RB

**Comment by mcrha** [comment]
> vapigen does not use the typelib, how did you trigger this issue?

Hmm, does it not? Weird, I though it does.

I do not know what causes it, some maybe system setting, or such, I only faced it while playing with these changes. When I disable parallel build it works. When I add the typelib dependency it works. Without it I _sometimes_ get during `make && make install`:
```
libical-glib-scan.c: In function ‘output_object_actions’:
libical-glib-scan.c:601:30: warning: unused parameter ‘fp’ [-Wunused-parameter]
  601 | output_object_actions (FILE *fp, GType object_type)
      |                        ~~~~~~^~

make[2]: *** [src/libical-glib/CMakeFiles/valafile.dir/build.make:75: src/libical-glib/libical-glib.vapi] Bus error (core dumped)
make[1]: *** [CMakeFiles/Makefile2:1080: src/libical-glib/CMakeFiles/valafile.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:146: all] Error 2
```
Maybe it's only a coincidence.

It's known the libical build can fail in parallel build due to the libical-glib internals (like https://github.com/libical/libical/issues/723), this vala related one was new to me. I've been thinking recently that mabe the dependencies on the files are not that deterministic. I do not know how CMake does it, but if it just waits for a file existence, then the following command can be run before the generator finishes writing to the file (that is what I suspect for the #723), thus if the tools would write to a temporary file and create the result as an "atomic" rename of the file, then it could, theoretically, fix the issues. This is all only a theory of me, most likely a wrong one.

**Comment by mcrha** [comment]
> other commits are RB

What does "RB" stand for here, please? "Look good" might be "LG", I guess.

**Comment by tintou** [comment]
Sorry, Rb is Reviewed-by, so looks good to me :)

**Comment by tintou** [comment]
Yes that's probably a racing issue because vapigen really only use the .gir file

**Pull request merged**
