### PR TITLE
Make icalrecurrencetype a type that is passed by ref rather than by val.

### PR DESCRIPTION
**Pull request by minichma**
Changes `icalrecurrencetype` to be passed by reference rather than by value. The concept is very close to how `icalattach` works. I.e.
* Instances of `struct icalrecurrencetype` are created `icalrecurrencetype_new()` or `icalrecurrencetype_new_from_string()`, which allocates them on the heap, rather than on the stack. New objects are returned with a refcount of 1.
* Memory is managed via reference counting (via `icalrecurrencetype_ref()` and `icalrecurrencetype_unref()`). Objects are automatically freed when the reference counter reaches 0. There is no explicit `icalrecurrencetype_free()` function.

The GLib API stays unchanged, except for the `i_cal_recurrence_clear()` method, which has been removed, as it doesn't seem to make too much sense now. The C version `icalrecurrencetype_clear` was mainly used to mark an object as undefined, which is now done by setting the pointer to NULL, so it has been removed. But that's TBD.

ToDo
- [x] Review GLib binding. I don't know too much about GLib in general and our bindings in particular, this should be reviewed carefully. Especially the initial reference counting and relation to the object's owner (compare the binding of icalattach, where we have this `new_full_extra_code="if (owner) { icalattach_ref (native); owner = NULL; }"`.
- [x] Update documentation and code comments.
- [x] Release notes.

Fixes https://github.com/libical/libical/issues/387

### CODE REVIEW

**Comment by minichma** [comment]
@winterz What do you think? Who would be the one having a closer look at the GLib binding? I'm not an expert there, so it should be reviewed carefully.

**Review by winterz — COMMENTED** [review]
looking now. 
I fixed up the .md file a bit and am currently working in a new branch called minichma-recur_byref

**Comment by minichma** [comment]
Great, thank you. Added two minor fixes onto minichma-recur_byref that I just came across, not too relevant. Should be squashed before merging.

**Comment by winterz** [comment]
we don't care about Java bindings at this time. (see issue #199)
nor Perl (#202)

you can remove the Java bindings from this issue's task list

**Comment by winterz** [comment]
so far I can't find any problems with glib implementation.
I think we go ahead with it and deal with any unforeseen problems in follow-on patches

**Comment by minichma** [comment]
Alright, should I reset this PR onto the minichma branch? And start a 4.0 section in the release notes?

**Comment by winterz** [comment]
> Alright, should I reset this PR onto the minichma branch?

yes.

>  And start a 4.0 section in the release notes?
hmm.. right, we need to rename "3.1" to "4.0" in the ReleaseNotes
for now just add to the list under "Version 3.1.0 (NOT RELEASED YET):" .  I'll eventually change that to "Version 4.0.0"

**Pull request merged**
