### PR TITLE
Bugfix: support malformed input with only CR and no LF 

### PR DESCRIPTION
**Pull request by Iridias**
Some servers (e.g. Kerio Connect) seem to send malformed data, containing only carriage returns but no line feeds.

I changed the line-parser to also support such input.
This should also solve this bug in Akonadi: https://bugs.kde.org/show_bug.cgi?id=325224
as it uses libical to parse the server-response.

### CODE REVIEW

**Comment by winterz** [comment]
thanks Iridias.
If you ever feel like adding a little test for this to regression.c I wouldn't mind at all :)
Please.

**Comment by manuelsongokuh** [comment]
sorry i need this please...  how i will can convert from source to binary (for opensuse moment)..
because my office job are 30 persons needed this fix..for korganizer..(did you read forum ? https://bugs.kde.org/show_bug.cgi?id=325224)

please respond me as soon..

**Comment by manuelsongokuh** [comment]
hello...nothing respond...??

**Comment by ichrispa** [comment]
Well, fyi, I'm stuck on the same problem as @manuelsongokuh...  though of course akonadi using libical-1.0 is not at all the libicals-team problem.

@winterz: Did you rebuild akonadi/kontact from scratch to get it to use libical2?

**Comment by winterz** [comment]
I use a hand-built KDE 4.14 and build against libical 2

proof
[463]$ ldd `which korganizer` | grep libical
        libical.so.2 => /data/mykde/lib64/libical.so.2 (0x00007f7b4e2da000)
        libicalss.so.2 => /data/mykde/lib64/libicalss.so.2 (0x00007f7b4e0c0000)
        libicalvcal.so.2 => /data/mykde/lib64/libicalvcal.so.2 (0x00007f7b4deaa00)

Sorry that I can't help you guys build on your various distros.

**Comment by ichrispa** [comment]
Hi @winterz,

    Sorry that I can't help you guys build on your various distros.

Not a problem at all :) I patched your change into the 1.0 tree and it turns out that this is not the source of my grief. But thank you anyway for the bugfix.

**Comment by manuelsongokuh** [comment]
hello
i wish to try if libical.so.2 on my opensuse 13.2 and kde 4.14.9, do you did created binary and can send me pack so i will copy and paste in path:
/usr/lib64/libical.so.1
/usr/lib64/libical.so.1.0.0
/usr/lib64/libicalss.so.1
/usr/lib64/libicalss.so.1.0.0
/usr/lib64/libicalvcal.so.1
/usr/lib64/libicalvcal.so.1.0.0
and i will can to see if worked for FIXED and i will tell here: OK or KO for korganizer, okay?
i wait you for binary..
thank you

**Comment by manuelsongokuh** [comment]
hello...nothing respond...??

**Comment by winterz** [comment]
I don't have an opensuse 13.2 system

**Comment by manuelsongokuh** [comment]
ok but you have file binary so i try with m opensuse 13.2, give me link
thank you

**Comment by winterz** [comment]
it simply won't work.  libical version 2 is not binary compatible .  you need to re-build the stack from libical all the way up to the application you want to use it in.

**Comment by manuelsongokuh** [comment]
ok, what is distro for re-build, so i will install centos in virtualbox for create re-build? sorry i want to use last version libical2 for TESTING..please i'm not expert, but if you can explain how does re-build it, so i try follow you steps..

**Comment by manuelsongokuh** [comment]
hello...nothing respond...??

**Comment by manuelsongokuh** [comment]
hello...nothing respond...??

**Comment by manuelsongokuh** [comment]
hello...nothing respond...??

**Comment by Iridias** [comment]
This is not a support-forum

**Comment by manuelsongokuh** [comment]
ok, where is forum support? maybe you are not understand. we are 40-60 employments to work with this libical for caldav in korganizer.. we wish to test it.. if worked or not work for save a lot of time..it's right or no?

**Pull request merged**
