### PR TITLE
Please make the typedef & include generation reproducible.

### PR DESCRIPTION
**Pull request by lamby**
Whilst working on the Reproducible Builds effort [0], we noticed
that libical3 could not be built reproducibly as it iterates over
the filesystem as well as iterates over the keys of a hash, both
of which are non-deterministic.

Patch attached.

 [0] https://reproducible-builds.org/

Filed in Debian as https://bugs.debian.org/889565

### CODE REVIEW

**Comment by winterz** [comment]
unfortunately travis-ci is showing segfaults
https://travis-ci.org/libical/libical/jobs/337225459, for example

**Comment by lamby** [comment]
Ah, can't reproduce that locally but by-inspection I think it was that `filenames` could be uninitialised. Trying again..

**Comment by lamby** [comment]
@winterz There you go :)

**Comment by winterz** [comment]
commited in sha 6659ae7d5d4289068c5a61bb27b885a4fc600ca6

**Comment by lamby** [comment]
Thanks :)

**Pull request merged**
