### PR TITLE
vCard API

### PR DESCRIPTION
**Pull request by ksmurchison**
Add new API for constructing/serializing vCard data, similar to the API for iCalendar data.

### CODE REVIEW

**Comment by ksmurchison** [comment]
@rsto This is now usable. 

It doesn't yet support multi-valued properties.  

It also currently treats structured property values (e.g. N, ADDR) and time value types (BDAY, ANNIVERSARY) as strings.

src/test/libicalvcard/vcard_test.c shows how to use both the parser and constructors

test-data/test.vcf is what I have been using for testing (its a work in progress)

**Comment by winterz** [comment]
I can look closer this weekend I hope
but the appveyor builds are very unhappy.

**Comment by ksmurchison** [comment]
I'm not familiar with appveyor.  Can I try to build it locallly?

**Comment by winterz** [comment]
> I'm not familiar with appveyor. Can I try to build it locallly?

https://ci.appveyor.com/project/winterz/libical/builds/44765460  has some hints.
I haven't tried building this patch on my local machines yet

**Comment by winterz** [comment]
- all new files are missing license+copyright header
- I like to order the includes by "own-first", for example in vcardstrarray.c change:
```
#include <string.h>
#include "icalmemory.h"
#include "vcardstrarray.h"
```
to
```
#include "vcardstrarray.h"
#include "icalmemory.h"
#include <string.h>
```

**Comment by ksmurchison** [comment]
@winterz I've fixed a bunch of the compiler issues, but I don't have a Windows dev environment, and I can't figure out why the code fails to compile.  I also don't know why the tests apparently crash on MacOS and on the Ubuntu Release build.  They pass reliably fir us on Fedora and Debian.  Can you lend any insight?

**Comment by ksmurchison** [comment]
@winterz I added license+copyright to the source code files in the hopes of finally getting this merged.
The failing vcard tests pass consistently on my Fedora box.  Ca you lend any insight to the issues?

**Comment by winterz** [comment]
I'll look closer.   
could you replace 'http://fastmail.com' with 'https://fastmail.com' in the copyright lines#ifdef HAVE_CONFIG_H
ssize_t isn't defined in some files (like vcard_test_encode.c). maybe you need to add at the top:

```
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
```

**Comment by ksmurchison** [comment]
@winterz Fixed the copyright, ssize_t and vcardcomponent.c issues, but the build tests are still failing.

Which compiler is being used and with what CFLAGS?

**Comment by winterz** [comment]
can you:

- merge against master (to get the cmake 3.19 requirement)
- merge against the cyrusimap-vcard branch where I've been adding a few changes to your patch

**Comment by ksmurchison** [comment]
> can you:
> 
>     * merge against master (to get the cmake 3.19 requirement)
> 
>     * merge against the cyrusimap-vcard branch where I've been adding a few changes to your patch

Done.

**Comment by winterz** [comment]
the mac compile failures should be fixed if you remove the config.h include at the top of vcardenumarray.h

I'm still stumped by the Windows linker error `warning C4211: nonstandard extension used: redefined extern to static`

the vcard_construct Subprocess aborted***Exception: in ubuntu release builder is something that we need to investigate closer.

**Comment by ksmurchison** [comment]
> the mac compile failures should be fixed if you remove the config.h include at the top of vcardenumarray.h

Done.

> I'm still stumped by the Windows linker error `warning C4211: nonstandard extension used: redefined extern to static`

I've looked and I can't find anything that is declared extern then static or vice-versa and came up empty.

> the vcard_construct Subprocess aborted***Exception: in ubuntu release builder is something that we need to investigate closer.

Yes, but I can't reproduce.  Can we get a core dump?

**Comment by winterz** [comment]
for the windows linking problem,  try adding the 1-line hack in #679

**Comment by winterz** [comment]
here's a bt for the vcard encode test crash:

```
Core was generated by `/home/allen/projects/libical/libical/build-test1memc-mem/src/test/vcard_test_en'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading source file /usr/src/debug/glibc-2.38-17.fc39.x86_64/nptl/pthread_kill.c...
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f49f46ae8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f49f465c8ee in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f49f46448ff in __GI_abort () at abort.c:79
#4  0x00007f49f46457d0 in __libc_message (fmt=fmt@entry=0x7f49f47c256a "%s\n") at ../sysdeps/posix/libc_fatal.c:150
#5  0x00007f49f46b87a5 in malloc_printerr (str=str@entry=0x7f49f47c4de8 "munmap_chunk(): invalid pointer") at malloc.c:5765
#6  0x00007f49f46b8a3c in munmap_chunk (p=p@entry=0x14af5d0) at malloc.c:3035
#7  0x00007f49f46bd42a in __GI___libc_free (mem=0x14af5e0) at malloc.c:3381
#8  0x00007f49f50831e5 in _parse_prop_value (state=0x7ffc57043670) at /home/allen/projects/libical/libical/src/libicalvcard/vcardparser.c:716
#9  0x00007f49f50821d1 in _parse_prop (state=0x7ffc57043670) at /home/allen/projects/libical/libical/src/libicalvcard/vcardparser.c:835
#10 0x00007f49f5081e75 in _parse_vcard (state=0x7ffc57043670, comp=0x14af680, only_one=0) at /home/allen/projects/libical/libical/src/libicalvcard/vcardparser.c:876
#11 0x00007f49f5081f15 in _parse_vcard (state=0x7ffc57043670, comp=0x14af440, only_one=0) at /home/allen/projects/libical/libical/src/libicalvcard/vcardparser.c:894
#12 0x00007f49f5081da6 in vcardparser_parse (state=0x7ffc57043670, only_one=0) at /home/allen/projects/libical/libical/src/libicalvcard/vcardparser.c:944
#13 0x00007f49f5081cbd in vcardparser_parse_string (str=0x401b59 "BEGIN:VCARD\r\nVERSION:3.0\r\nN:y,\\,\\\\;\\;,\\n\\N\r\nEND:VCARD\r\n") at /home/allen/projects/libical/libical/src/libicalvcard/vcardparser.c:1014
#14 0x0000000000400de8 in ?? ()
#15 0x00000000014af600 in ?? ()
#16 0x00000000014af440 in ?? ()
#17 0x00007ffc57043740 in ?? ()
#18 0x00007f49f507f05f in vcardcomponent_free (c=0x14af440) at /home/allen/projects/libical/libical/src/libicalvcard/vcardcomponent.c:167

```

**Comment by winterz** [comment]
in vcardtime.c please use gmtime_r() instead of gmtime()

**Comment by ksmurchison** [comment]
@winterz what's at your line 716 of vcardparser.c?  I'm seeing buf_reset() which doesn't call malloc().

**Comment by ksmurchison** [comment]
> in vcardtime.c please use gmtime_r() instead of gmtime()

I decided to use icalgmtime_r()

**Comment by winterz** [comment]
> @winterz what's at your line 716 of vcardparser.c? I'm seeing buf_reset() which doesn't call malloc().

right.  I'll get you a new backtrace.

**Comment by winterz** [comment]
I notice you're hard-coding the integer 21 in a few places.
can you use a macro for that instead?

**Comment by winterz** [comment]
I found mis-usage of free() in _parse_prop_value.   replacing free() with icalmemory_free_buffer() seems to help

do another merge against the cyrusimap-vcard branch

**Comment by winterz** [comment]
when doing a build with fortify compile options I see:
```
/home/allen/projects/libical/libical/src/test/libicalvcard/vcard_test.c:56:5: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
/usr/include/bits/unistd.h:28:10: warning: ‘__read_alias’ specified size 18446744073709551614 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
```

**Comment by winterz** [comment]
ASAN build problem with vcard_construct test:

```
Test project /home/allen/projects/libical/libical/build-test1asan-asan
    Start 46: vcard_construct
1/1 Test #46: vcard_construct ..................***Failed    0.07 sec
=================================================================
==421939==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f8f05fea430 at pc 0x7f8f05fd128f bp 0x7fff7a1603e0 sp 0x7fff7a1603d8
READ of size 4 at 0x7f8f05fea430 thread T0
    #0 0x7f8f05fd128e in vcardrestriction_get_restriction /home/allen/projects/libical/libical/build-test1asan-asan/src/libicalvcard/vcardrestriction.c:322
    #1 0x7f8f05fd128e in vcardrestriction_check_component /home/allen/projects/libical/libical/build-test1asan-asan/src/libicalvcard/vcardrestriction.c:233
    #2 0x401b29 in main /home/allen/projects/libical/libical/src/test/libicalvcard/vcard_test.c:68
    #3 0x7f8f05646149 in __libc_start_call_main (/lib64/libc.so.6+0x28149) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
    #4 0x7f8f0564620a in __libc_start_main_impl (/lib64/libc.so.6+0x2820a) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
    #5 0x402444 in _start (/home/allen/projects/libical/libical/build-test1asan-asan/src/test/vcard_test+0x402444) (BuildId: e4a96d9e157f698c52850d8b6c6ce27cffbb4021)

0x7f8f05fea430 is located 16 bytes before global variable 'value_map' defined in '/home/allen/projects/libical/libical/build-test1asan-asan/src/libicalvcard/vcardderivedvalue.c:36:41' (0x7f8f05fea440) of size 552
0x7f8f05fea430 is located 16 bytes after global variable 'null_restriction_record' defined in '/home/allen/projects/libical/libical/build-test1asan-asan/src/libicalvcard/vcardrestriction.c:44:38' (0x7f8f05fea400) of size 32
SUMMARY: AddressSanitizer: global-buffer-overflow /home/allen/projects/libical/libical/build-test1asan-asan/src/libicalvcard/vcardrestriction.c:322 in vcardrestriction_get_restriction
Shadow bytes around the buggy address:
  0x7f8f05fea180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f8f05fea200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f8f05fea280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f8f05fea300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f8f05fea380: 00 00 00 04 f9 f9 f9 f9 00 00 00 03 f9 f9 f9 f9
=>0x7f8f05fea400: 00 00 00 00 f9 f9[f9]f9 00 00 00 00 00 00 00 00
  0x7f8f05fea480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f8f05fea500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f8f05fea580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f8f05fea600: 00 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9
  0x7f8f05fea680: f9 f9 f9 f9 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==421939==ABORTING
```

**Comment by winterz** [comment]
cppcheck is complaining about:
```
/home/allen/projects/libical/libical/src/libicalvcard/vcardvalue.c:220,warning,uninitvar,Uninitialized variable: *str_p
```

looks like a false positive to me.

**Comment by winterz** [comment]
could you merge  against the cyrusimap-vcard branch again? I think I hacked around in vcard_test.c to make the fortify build happy.  also I'm not seeing some fixes for splint in your fork for some reason.

**Comment by ksmurchison** [comment]
> could you merge  against the cyrusimap-vcard branch again? I think I hacked around in vcard_test.c to make the fortify build happy.  also I'm not seeing some fixes for splint in your fork for some reason.

About to hop on a flight. Probably won't look at this until tomorrow. Thanks for the help!

**Comment by winterz** [comment]
the asan problems are in vcardrestriction_check_component, somewhere in the "Now check the inner components" section.   

another question about vcardrestriction_check_component: we are passing 'vcardproperty_version version' but that value is never used and instead we have code to compute the version from the version_prop:
```
    if (version_prop == NULL) {
        version = VCARD_VERSION_NONE;
    } else {
        version = vcardproperty_get_version(version_prop);
    }
```

**Comment by winterz** [comment]
this fixes the asan failure:
```
     /* Now check the inner components */
 
-    start_record = vcardrestriction_get_restriction(start_record,
+    start_record = vcardrestriction_get_restriction(NULL,
```

I have no idea if this is the right thing to do

**Comment by ksmurchison** [comment]
> this fixes the asan failure:
> 
> ```
>      /* Now check the inner components */
>  
> -    start_record = vcardrestriction_get_restriction(start_record,
> +    start_record = vcardrestriction_get_restriction(NULL,
> ```
> 
> I have no idea if this is the right thing to do

I thought about that this mirning and I expected that would fix it, but it eliminates that shortcut that I was trying to implement.  I'm going to do some more debugging on this.

**Comment by winterz** [comment]
in vcardtime.c  sprintf_date()  a few of the fmt strings are using '$N' .  I assume you mean '%N'?
ie.
```
index 9a5b7b93..20431a56 100644
--- a/src/libicalvcard/vcardtime.c
+++ b/src/libicalvcard/vcardtime.c
@@ -152,13 +152,14 @@ static int sprintf_date(const vcardtimetype t, char *buf, size_t size)
     else {
         strcat(fmt, "--");
 
-        strcat(fmt, (t.month != -1) ? "%2$02d" : "-");
+        strcat(fmt, (t.month != -1) ? "%2%02d" : "-");
 
         if (t.day != -1) {
-            strcat(fmt, "%3$02d");
+            strcat(fmt, "%3%02d");
         }
     }
 
```

**Comment by ksmurchison** [comment]
> in vcardtime.c sprintf_date() a few of the fmt strings are using '$N' . I assume you mean '%N'? ie.

No, $N specifies the argument number that has the data for the given format element.  If you look closely, you'll see that i some cases there will be more arguments than format elements.

**Comment by winterz** [comment]
> > in vcardtime.c sprintf_date() a few of the fmt strings are using '$N' . I assume you mean '%N'? ie.
> 
> No, $N specifies the argument number that has the data for the given format element. If you look closely, you'll see that i some cases there will be more arguments than format elements.

hmm.. because fortify compiles are complaining about the '$N'
so far my web searches aren't finding any hints on how to avoid this,  we cold add ifdefs on_FORTIFY_SOURCE

**Comment by winterz** [comment]
"%2$02d" is an illegal format.  do you want to print the '%' char?  then you want '%%2$02d'.  do you want to print an integer? then you need '%2d$02d"
anyway, I think fortify is correct to complain

**Comment by ksmurchison** [comment]
> "%2$02d" is an illegal format. do you want to print the '%' char? then you want '%%2$02d'. do you want to print an integer? then you need '%2d$02d" anyway, I think fortify is correct to complain

Neither.  Its says "print the second argument with the format %02d:.  From the printf(3) manpage:
`      The overall syntax of a conversion specification is:

           %[$][flags][width][.precision][length modifier]conversion

       The  arguments  must correspond properly (after type promotion) with the conversion specifier.  By default, the arguments
       are used in the order given, where each '*' (see Field width and Precision below) and each conversion specifier asks  for
       the next argument (and it is an error if insufficiently many arguments are given).  One can also specify explicitly which
       argument is taken, at each place where an argument is required, by writing "%m$" instead of '%' and "*m$" instead of '*',
       where  the  decimal integer m denotes the position in the argument list of the desired argument, indexed starting from 1.
       Thus,

           printf("%*d", width, num);

       and

           printf("%2$*1$d", width, num);

       are equivalent.  The second style allows repeated references to the same argument.  The C99 standard does not include the
       style  using  '$',  which  comes  from  the  Single  UNIX Specification.  If the style using '$' is used, it must be used
       throughout for all conversions taking an argument and all width and precision arguments, but it may be  mixed  with  "%%"
       formats, which do not consume an argument.  There may be no gaps in the numbers of arguments specified using '$'; for ex‐
       ample, if arguments 1 and 3 are specified, argument 2 must also be specified somewhere in the format string.
`

**Comment by winterz** [comment]
learn something new..

that same man page says "The C99 standard does not include the style using '$', which  comes  from the  Single UNIX Specification" and we are specifically compiling with strict C99.  I'll try removing the strict c99 requirement to see if that helps

**Comment by winterz** [comment]
> learn something new..
> 
> that same man page says "The C99 standard does not include the style using '$', which comes from the Single UNIX Specification" and we are specifically compiling with strict C99. I'll try removing the strict c99 requirement to see if that helps

no, removing the C99 requirement didn't help

**Comment by ksmurchison** [comment]
> > learn something new..
> > that same man page says "The C99 standard does not include the style using '$', which comes from the Single UNIX Specification" and we are specifically compiling with strict C99. I'll try removing the strict c99 requirement to see if that helps
> 
> no, removing the C99 requirement didn't help

I'm rewriting vcardtime.c to NOT use %m$

**Comment by ksmurchison** [comment]
> > > learn something new..
> > > that same man page says "The C99 standard does not include the style using '$', which comes from the Single UNIX Specification" and we are specifically compiling with strict C99. I'll try removing the strict c99 requirement to see if that helps
> > 
> > 
> > no, removing the C99 requirement didn't help
> 
> I'm rewriting vcardtime.c to NOT use %m$

Done.

**Comment by winterz** [comment]
> > > > learn something new..
> > > > that same man page says "The C99 standard does not include the style using '$', which comes from the Single UNIX Specification" and we are specifically compiling with strict C99. I'll try removing the strict c99 requirement to see if that helps
> > > 
> > > 
> > > no, removing the C99 requirement didn't help
> > 
> > 
> > I'm rewriting vcardtime.c to NOT use %m$
> 
> Done.

you're using %2u to print signed integers in many places , for example:
```
src/libicalvcard/vcardtime.c: (in function sscanf_date)
src/libicalvcard/vcardtime.c:308:41: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->day
  To ignore signs in type comparisons use +ignoresigns
   src/libicalvcard/vcardtime.c:308:35: Corresponding format code
src/libicalvcard/vcardtime.c:315:43: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->month
   src/libicalvcard/vcardtime.c:315:34: Corresponding format code
src/libicalvcard/vcardtime.c:315:54: Format argument 2 to sscanf (%2u) expects unsigned int * gets int *: &t->day
   src/libicalvcard/vcardtime.c:315:37: Corresponding format code
src/libicalvcard/vcardtime.c:318:40: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->month
```

**Comment by ksmurchison** [comment]
> > > > > learn something new..
> > > > > that same man page says "The C99 standard does not include the style using '$', which comes from the Single UNIX Specification" and we are specifically compiling with strict C99. I'll try removing the strict c99 requirement to see if that helps
> > > > 
> > > > 
> > > > no, removing the C99 requirement didn't help
> > > 
> > > 
> > > I'm rewriting vcardtime.c to NOT use %m$
> > 
> > 
> > Done.
> 
> you're using %2u to print signed integers in many places , for example:
> 
> ```
> src/libicalvcard/vcardtime.c: (in function sscanf_date)
> src/libicalvcard/vcardtime.c:308:41: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->day
>   To ignore signs in type comparisons use +ignoresigns
>    src/libicalvcard/vcardtime.c:308:35: Corresponding format code
> src/libicalvcard/vcardtime.c:315:43: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->month
>    src/libicalvcard/vcardtime.c:315:34: Corresponding format code
> src/libicalvcard/vcardtime.c:315:54: Format argument 2 to sscanf (%2u) expects unsigned int * gets int *: &t->day
>    src/libicalvcard/vcardtime.c:315:37: Corresponding format code
> src/libicalvcard/vcardtime.c:318:40: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->month
> ```

So, the fields in the struct are signed because we use -1 to mean that the value is unset.  We use %u to parse the values because we always want to parse as a 2/4 digit unsigned value (we don't want to parse a "-").

Is your compiler happy if you type-cast the pointer, E.g., (unsigned *)  &t->month

**Comment by winterz** [comment]
> > > > > > learn something new..
> > > > > > that same man page says "The C99 standard does not include the style using '$', which comes from the Single UNIX Specification" and we are specifically compiling with strict C99. I'll try removing the strict c99 requirement to see if that helps
> > > > > 
> > > > > 
> > > > > no, removing the C99 requirement didn't help
> > > > 
> > > > 
> > > > I'm rewriting vcardtime.c to NOT use %m$
> > > 
> > > 
> > > Done.
> > 
> > 
> > you're using %2u to print signed integers in many places , for example:
> > ```
> > src/libicalvcard/vcardtime.c: (in function sscanf_date)
> > src/libicalvcard/vcardtime.c:308:41: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->day
> >   To ignore signs in type comparisons use +ignoresigns
> >    src/libicalvcard/vcardtime.c:308:35: Corresponding format code
> > src/libicalvcard/vcardtime.c:315:43: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->month
> >    src/libicalvcard/vcardtime.c:315:34: Corresponding format code
> > src/libicalvcard/vcardtime.c:315:54: Format argument 2 to sscanf (%2u) expects unsigned int * gets int *: &t->day
> >    src/libicalvcard/vcardtime.c:315:37: Corresponding format code
> > src/libicalvcard/vcardtime.c:318:40: Format argument 1 to sscanf (%2u) expects unsigned int * gets int *: &t->month
> > ```
> 
> So, the fields in the struct are signed because we use -1 to mean that the value is unset. We use %u to parse the values because we always want to parse as a 2/4 digit unsigned value (we don't want to parse a "-").
> 
> Is your compiler happy if you type-cast the pointer, E.g., (unsigned *) &t->month

should be fixed with lots of casting in the cyrusimap-vcard branch.  please merge that branch (again)

**Comment by ksmurchison** [comment]
@winterz Looks like we're getting closer.  The tests no longer appear to be crashing in vcardrestriction_check().

Any idea why the test on Windows won't complete?

**Comment by winterz** [comment]
> @winterz Looks like we're getting closer. The tests no longer appear to be crashing in vcardrestriction_check().
> 
> Any idea why the vcard_construct tests on Windows won't complete?

not yet.  will look closer tomorrow.

**Comment by ksmurchison** [comment]
> > @winterz Looks like we're getting closer. The tests no longer appear to be crashing in vcardrestriction_check().
> > Any idea why the vcard_construct tests on Windows won't complete?
> 
> not yet. will look closer tomorrow.

Is there any way that I can re-run the vcard_construct test on GitHub with more info?  Should I add some debugging printf()'s to the source?

**Comment by ksmurchison** [comment]
> > > > @winterz Looks like we're getting closer. The tests no longer appear to be crashing in vcardrestriction_check().
> > > > Any idea why the vcard_construct tests on Windows won't complete?
> > > 
> > > 
> > > not yet. will look closer tomorrow.
> > 
> > 
> > Is there any way that I can re-run the vcard_construct test on GitHub with more info? Should I add some debugging printf()'s to the source?
> 
> I tried locally on my Windows laptop and all the tests are aok. I'll add ctest -VV to the github workflow to see if that gives any hints

Where does that get logged?

**Comment by ksmurchison** [comment]
@winterz I added a printf() to spit out the partially parsed vCard, but I can't find in the GitHub UI where to get the link for the log that shows the assert() or my printf()

**Comment by ksmurchison** [comment]
> @winterz I added a printf() to spit out the partially parsed vCard, but I can't find in the GitHub UI where to get the link for the log that shows the assert() or my printf()

Never mind.  I hadn't rebased in your branch to get `ctest -VV`

**Comment by ksmurchison** [comment]
So, the vCard appears to be parsed correctly except vcardparser_parse() is returning a non-zero value.  I'm guessing some Windows EOL (CR/LF) and/or EOF issue.  Will keep digging

**Comment by ksmurchison** [comment]
@winterz Here's the problem:
`43: parse vcard(BEGIN:VCARD
43: VERSION: 4.0
43: FN:Simon Perreault
43: N:Perreault;Simon;;;ing. jr,M.Sc.
43: BDAY:--0203
43: BDAY:--0203
43: ANNIVERSARY:20090808T1430-0500
43: GENDER:M;manly
43: LANG;PREF=1:fr
43: LANG;PREF=2:en
43: ORG;TYPE=work:Viagenie;Foo
43: ADR;TYPE=work:;Suite D2-630;2875 Laurier;
43:  Quebec;QC;G1V 2M2;Canada
43: TEL;VALUE=URI;TYPE=voice;PREF=100:tel:+1-418-656-9254;ext=102
43: TEL;VALUE=URI;TYPE="work,cell,foo,voice,bar,video,text":tel:+1-418-262-6501
43: EMAIL;TYPE=WORK:simon.perreault@viagenie.ca
43: GEO;TYPE=WORK:geo:46.772673,-71.282945
43: KEY;TYPE=WORK:http://www.viagenie.ca/simon.perreault/simon.asc
43: TZ:-0500
43: 
43: URL;TYPE=HOME:http://nomis80.org/
43: NOTE;LANGUAGE=en;PID=3,1.0:Test vCard
43: CATEGORIES:foo,bar
43: END:VCARD
43: 
43: BEGIN:VCARD
43: FN:Mickey Mouse
43: END:VCARD
43: FN:Mickey Mouse
43: END:VCARD
43: )
43: p: 'B'
43: _parse_prop_name: 0  'BEGIN'
43: BEGIN val: 'VCARD'
43: parse vcard(VERSION: 4.0
43: FN:Simon Perreault
43: N:Perreault;Simon;;;ing. jr,M.Sc.
43: BDAY:--0203
43: BDAY:--0203
43: ANNIVERSARY:20090808T1430-0500
43: GENDER:M;manly
43: LANG;PREF=1:fr
43: LANG;PREF=2:en
43: ORG;TYPE=work:Viagenie;Foo
43: ADR;TYPE=work:;Suite D2-630;2875 Laurier;
43:  Quebec;QC;G1V 2M2;Canada
43: TEL;VALUE=URI;TYPE=voice;PREF=100:tel:+1-418-656-9254;ext=102
43: TEL;VALUE=URI;TYPE="work,cell,foo,voice,bar,video,text":tel:+1-418-262-6501
43: EMAIL;TYPE=WORK:simon.perreault@viagenie.ca
43: GEO;TYPE=WORK:geo:46.772673,-71.282945
43: KEY;TYPE=WORK:http://www.viagenie.ca/simon.perreault/simon.asc
43: TZ:-0500
43: 
43: URL;TYPE=HOME:http://nomis80.org/
43: NOTE;LANGUAGE=en;PID=3,1.0:Test vCard
43: CATEGORIES:foo,bar
43: END:VCARD
43: 
43: BEGIN:VCARD
43: FN:Mickey Mouse
43: END:VCARD
43: FN:Mickey Mouse
43: END:VCARD
43: )`

The data that gets loaded from the file duplicates the last two lines.  I haven't figured out how/why yet.

**Comment by ksmurchison** [comment]
So, here is the issue: `read 706 of 734 bytes`
The size we get from fstat() is apparently larger than the actual file size.

**Comment by winterz** [comment]
> @winterz So, here is the issue: `read 706 of 734 bytes` The size we get from fstat() is apparently larger than the actual file size. I tried to truncate data to the size we get from read() but it didn't fix it: [b767651](https://github.com/libical/libical/commit/b7676510b0191dc5d190282d6c287c52233766f9)
> 
> Any ideas?

I just committed stuff that forces Windows to pickup _fstat64 in the cyrus_vcard branch. please merge that

**Comment by winterz** [comment]
> > @winterz So, here is the issue: `read 706 of 734 bytes` The size we get from fstat() is apparently larger than the actual file size. I tried to truncate data to the size we get from read() but it didn't fix it: [b767651](https://github.com/libical/libical/commit/b7676510b0191dc5d190282d6c287c52233766f9)
> > Any ideas?
> 
> I just committed stuff that forces Windows to pickup _fstat64 in the cyrus_vcard branch. please merge that

didn't work .  

New idea: is git adding/removing CRLFs from the test.vcf file?
the "wanted" data has "\r\n" EOLs.  so maybe we need to make sure the test.vcf is committed with CRLFs?

**Comment by ksmurchison** [comment]
Are you thinking DOS vs Unix thing?

**Comment by winterz** [comment]
I tried using .gitattributes to make sure test.vcf is a windows file.  when I do that the test asserts here on my Windows laptop.  maybe I'm going the wrong direction.  I'll try "\n" instead of "\r\n"

**Comment by winterz** [comment]
think I found it.  on windows we need to open the file in binary, not text mode.

from the `_read` doc (https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/read?view=msvc-170)
```
_read returns the number of bytes read, which might be less than buffer_size if there
are fewer than  buffer_size bytes left in the file, or if the file was opened in text mode.
In text mode, each carriage return-line feed pair \r\n is replaced with a single line
feed character \n. Only the single line feed character is counted in the return value.
The replacement doesn't affect the file pointer.
```

testing that in the cyrus_vcard branch

**Comment by winterz** [comment]
https://github.com/libical/libical/actions/runs/8860632277 all green!

**Comment by ksmurchison** [comment]
@winterz cleaned up all of my debugging junk and force pushed a clean vcard branch

The only other thing that I might do is add a v3/v4 flag to the serialization functions to output a proper v3/v4 card (E.g. PHOTO from data: URI to VALUE=BINARY, GEO from geo URI to "lat;lon", etc), so an app could ingest a v4 card and then output it as v3, and vice-versa.

**Comment by winterz** [comment]
> @winterz cleaned up all of my debugging junk and force pushed a clean vcard branch
> 
> The only other thing that I might do is add a v3/v4 flag to the serialization functions to output a proper v3/v4 card (E.g. PHOTO from data: URI to VALUE=BINARY, GEO from geo URI to "lat;lon", etc), so an app could ingest a v4 card and then output it as v3, and vice-versa.

good idea.
ok by me if you want to merge this one now and add the v3/v4 flag with a follow-on patch.
or wait.  either is fine.

**Comment by ksmurchison** [comment]
@winterz I added a vcardcomponent_transform() function to this PR for converting between v3 and v4.
Is now a good time to merge?

**Review by winterz — APPROVED** [review]

**Pull request merged**
