### PR TITLE
 [libical-glib] Make the library even easier to use with bindings

### PR DESCRIPTION
**Pull request by tintou**
With this set of changes, the library is even easier to use with Vala and hopefully with many languages using the GObject introspection.
Description of the change:
 * Provide a metadata file for Vala to fix some method misplacement
 * Created a helper to make ICalAttach objects from GBytes (used in many GLib-based libraries)
 * Fixed several annotations and added a delegate to document and have explicit types for callbacks
 * Renamed some functions (and sometimes diverge a little bit from libical itself) to respect the objects namespaces
 * Removed the langbind wrapper as the GObject introspection itself covers the functions

### CODE REVIEW

**Comment by winterz** [comment]
@tintou 
I'm seeing crashes in both the 3.0 and master branches when I configure with cmake '-DCMAKE_BUILD_TYPE=Debug -DGOBJECT_INTROSPECTION=True -DUSE_BUILTIN_TZDATA=OFF -DICAL_GLIB_VAPI=ON"

can you reproduce the crash? if so, can you fix?
I have glib2.0 2.64.6 and gobject-introspection-1.0 1.64.1 on Fedora 32

**Comment by tintou** [comment]
I have no issue here (tried with the latest commit on 3.0 branch). I'm on Ubuntu 20.04 so I have glib 2.66.0 and GObject Introspection 1.64.1. I'm using Evolution to test it though so you might use a path not covered by it. If you've a backtrace I'm happy to help.

**Comment by winterz** [comment]
To be more precise, the crash happens from vapigen during the build process..  Here's what I get in the master branch.
```
Core was generated by `/usr/bin/vapigen --vapidir=/home/allen/projects/libical/libical/src/libical-gli'.
Program terminated with signal SIGBUS, Bus error.
#0  0x00007fd24ca1324e in vala_markup_reader_space () from /lib64/libvala-0.48.so.0
#0  0x00007fd24ca1324e in vala_markup_reader_space () at /lib64/libvala-0.48.so.0
#1  0x00007fd24ca14061 in vala_markup_reader_read_token () at /lib64/libvala-0.48.so.0
#2  0x00007fd24c9c5a0e in vala_gir_parser_next () at /lib64/libvala-0.48.so.0
#3  0x00007fd24c9ceda4 in vala_gir_parser_parse_function () at /lib64/libvala-0.48.so.0
#4  0x00007fd24c9d52c4 in vala_gir_parser_parse_namespace () at /lib64/libvala-0.48.so.0
#5  0x00007fd24c9dbef8 in vala_gir_parser_parse_file () at /lib64/libvala-0.48.so.0
#6  0x00007fd24c993a69 in vala_code_context_accept () at /lib64/libvala-0.48.so.0
#7  0x00007fd24c9db2e6 in vala_gir_parser_parse () at /lib64/libvala-0.48.so.0
#8  0x0000562fcb65a30b in  ()
#9  0x0000562fcb9d2830 in  ()
#10 0x000000009ee99600 in  ()
#11 0x00007fd24c906090 in handler_hash () at /lib64/libgobject-2.0.so.0
#12 0x0000562fcd2fcde0 in  ()
#13 0x0000000000000008 in  ()
#14 0x00007fff132f5cc0 in  ()
#15 0x00007fff132f5de8 in  ()
#16 0x00007fff132f5e48 in  ()
#17 0x000000014c937bf8 in  ()
#18 0x00007fff132f5de8 in  ()
#19 0x0000000000000000 in  ()```

**Comment by tintou** [comment]
No issue here, I have:
```
vapigen --version
Vala API Generator 0.48.13
```
Have you enabled the updates on your Fedora 32, it seems that you can have at least Vala 0.48.12

**Comment by winterz** [comment]
yes, I have vala 0.48.12  according to rpm

oh well.  I'm stumped for now

**Pull request merged**
