### PR TITLE
Don't allow both COUNT and UNTIL in RRULE

### PR DESCRIPTION
**Pull request by ksmurchison**
Potential fix for issue #370

### CODE REVIEW

**Comment by winterz** [comment]
can you add some regression testing?

**Comment by ksmurchison** [comment]
@winterz  Are the tests that I added sufficient?  Shall I merge this branch?

**Comment by winterz** [comment]
> @winterz Are the tests that I added sufficient? Shall I merge this branch?

Yes! thanks.
could you merge to the 3.0 branch?
If not,I'll take care of merging it from master -> 3.0 myself.

**Comment by ksmurchison** [comment]
@winterz  I'll let you deal with 3.0

**Comment by winterz** [comment]
I cherry-picked to to the 3.0 branch.
the patch worked fine.  the compile worked fine.

however the regression test segfaults

```
#0  0x00007fcb3b4a93b3 in icalvalue_get_recur (value=0x8cd780) at /home/allen/projects/libical/libical/build-3.0-gcc/src/libical/icalderivedvalue.c:994
994         return *(value->data.v_recur);
```

**Comment by ksmurchison** [comment]
You cherry-picked all 3 commits?  The rrule_until+count branch doesn't fail for me.

**Comment by winterz** [comment]
I think so.
Please see the 3.0-backports branch.    I put all 3 commits in there.

**Comment by ksmurchison** [comment]
It doesn't look like you pushed that branch.

**Comment by winterz** [comment]
I see https://github.com/libical/libical/tree/3.0-backports

**Comment by ksmurchison** [comment]
Cherry-picked one more commit which fixes the regression crasher

**Pull request merged**
