### PR TITLE
issue #428: ignore BYYEARDAY when used with FREQ=MONTHLY

### PR DESCRIPTION
**Pull request by ksmurchison**
Possible fix if we choose to support this

### CODE REVIEW

**Comment by ksmurchison** [comment]
Are there any other combinations that we want to ignore, e.g. FREQ=DAILY;BYYEARDAY  ?

**Comment by ksmurchison** [comment]
@winterz @ksuther  Before I merge, any thoughts on my question above re: other bogus combos to ignore?

**Comment by ksuther** [comment]
We could mark all of the N/A rules as ignored. This would mean ignoring BYWEEKNO and BYMONTHDAY and adding BYYEARDAY in a couple more cases.

I don't know if that would get us into trouble with valid recurrences somehow, but it would make RRULE evaluation very lenient.

I can't think of any obvious problem with doing this, as just pretending they don't exist doesn't affect the valid parts of the RRULE.

```
      The term "N/A" means that the corresponding BYxxx rule part MUST
      NOT be used with the corresponding FREQ value.

      BYDAY has some special behavior depending on the FREQ value and
      this is described in separate notes below the table.

   +----------+--------+--------+-------+-------+------+-------+------+
   |          |SECONDLY|MINUTELY|HOURLY |DAILY  |WEEKLY|MONTHLY|YEARLY|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYMONTH   |Limit   |Limit   |Limit  |Limit  |Limit |Limit  |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYWEEKNO  |N/A     |N/A     |N/A    |N/A    |N/A   |N/A    |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYYEARDAY |Limit   |Limit   |Limit  |N/A    |N/A   |N/A    |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYMONTHDAY|Limit   |Limit   |Limit  |Limit  |N/A   |Expand |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYDAY     |Limit   |Limit   |Limit  |Limit  |Expand|Note 1 |Note 2|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYHOUR    |Limit   |Limit   |Limit  |Expand |Expand|Expand |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYMINUTE  |Limit   |Limit   |Expand |Expand |Expand|Expand |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYSECOND  |Limit   |Expand  |Expand |Expand |Expand|Expand |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYSETPOS  |Limit   |Limit   |Limit  |Limit  |Limit |Limit  |Limit |
   +----------+--------+--------+-------+-------+------+-------+------+
```

**Comment by winterz** [comment]
heck, I'm still dealing with the idea that there are lots of calendars out there with missing UIDs on their components.

I'm happy with whatever you and @ksuther think is best.

**Comment by ksmurchison** [comment]
I hate to blindly overlook bad client behavior without good reason, but I also subscribe to lenient in what we accept.  Have you tried running the test suite with all of the ILLEGAL changed to IGNORE?

**Comment by minichma** [comment]
I feel that there's no good 'fits all' solution. While I see, that there are good reasons for being compatible with Apple and Google, there are certainly scenarios where being more stringent is the right way to go. What about making the behavior (lenient vs stringent) configurable, either at build or in the field? If configured lenient, we would ignore *all* `ILLEGAL` combinations and if configured stringent, we would reject all of them.

**Comment by ksmurchison** [comment]
I had thought about making it configurable at compile time.  I'll take a look at that

**Comment by ksmurchison** [comment]
Superseded by #445

**Pull request closed without merging**
