### PR TITLE
icalrecur.c: fix for issue #782

### PR DESCRIPTION
**Pull request by ksmurchison**

### CODE REVIEW

**Comment by winterz** [comment]
lgtm
@minichma go ahead and merge if okay with you.

**Review by minichma — APPROVED** [review]

**Comment by minichma** [comment]
Looks great, thanks! So that the code used to work for the ICU case was due to the fact that `__icaltime_from_day_of_year` set sthe 1st doy as a side effect, right? Not quite obvious from the function name. Moreover the function is never used for getting an icaltime for a doy as the name suggests. Its only used for getting the weekno. The name could be updated for clarity in some future PR.

**Comment by minichma** [comment]
> go ahead and merge if okay with you.

@winterz After sleeping over it, I'm not sure whether you asked me to merge or just to state, whether I'm ok with it. 😆 Anyhow, the PR is merged. Is everything the way it should be? Is there anything else to do? Needs to be merged back to 3.0?

**Comment by winterz** [comment]
> > go ahead and merge if okay with you.
> 
> @winterz After sleeping over it, I'm not sure whether you asked me to merge or just to state, whether I'm ok with it. 😆 Anyhow, the PR is merged. Is everything the way it should be? Is there anything else to do? 

I meant for you to merge.  all good.
unless you think this is worthy of a mention in the ReleaseNotes


> Needs to be merged back to 3.0?

yes.  cherry-picked.
would you like to do that?

**Comment by minichma** [comment]
All good then. I feel this is too subtle to require release notes.

>> Needs to be merged back to 3.0?
>
>yes. cherry-picked.
would you like to do that?

Sure, happy to. Cherry-picked into 3.0.

**Pull request merged**
